# Generated by Django 3.1.1 on 2020-10-08 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_circle_comment_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_user_followings_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Circle',
        ),
    ]
